# This is a sample build configuration for Scala.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - sbt assembly
        artifacts:
          - target/scala-2.12/diceware-server.jar
    - step:
        script:
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/yannispollfish/diceware/downloads" --form files=@"target/scala-2.12/diceware-server.jar"

