lazy val root = Project("diceware", file("."))
//  .enablePlugins(ScroogeSBT)
  .settings(scalaVersion := "2.12.8")
  .settings(libraryDependencies += Dependencies.Thrift)
  .settings(libraryDependencies ++= Dependencies.Finagle)
  .settings(libraryDependencies ++= Dependencies.Scrooge)
  .settings(libraryDependencies ++= Dependencies.Logging)
  .settings(libraryDependencies ++= Dependencies.Twitter)
  .settings(libraryDependencies ++= Dependencies.Logging)
  .settings(libraryDependencies += Dependencies.TypesafeConfig)
