name: Diceware CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Assembly
        run: sbt assembly
      - uses: actions/upload-artifact@v1
        with:
          name: diceware-server
          path: server/target/scala-2.12/diceware-server.jar


