name: Diceware CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: npm install
        run: npm install
        working-directory: ./ui
      - name: Build ui
        run: npm run build
        working-directory: ./ui
      - name: Copy ui artifacts
        run: npm run copy
        working-directory: ./ui
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Assembly
        run: sbt assembly
      - uses: actions/upload-artifact@v1
        with:
          name: diceware-server
          path: server/target/scala-2.12/diceware-server.jar
